-- DATA MIGRATION SCRIPT: MySQL -> Supabase (PostgreSQL)
-- 1. Schema Updates (to match the richer data from the old site)
-- 2. Data Cleaning (Truncate existing placeholder data)
-- 3. Data Insertion (Real content)

-- ==========================================
-- 1. SCHEMA UPDATES
-- ==========================================

-- Table: services
-- Needs: full_description, requirements, benefits, image_url, is_active
ALTER TABLE public.services 
ADD COLUMN IF NOT EXISTS full_description TEXT,
ADD COLUMN IF NOT EXISTS requirements TEXT,
ADD COLUMN IF NOT EXISTS benefits TEXT,
ADD COLUMN IF NOT EXISTS image_url TEXT,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true;

-- Table: testimonials
-- Needs: photo_url (check if exists), is_active
ALTER TABLE public.testimonials
ADD COLUMN IF NOT EXISTS photo_url TEXT,
ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true;

-- Table: articles
-- Needs: content, meta_title, meta_description, keywords, is_published boolean fix
ALTER TABLE public.articles
ADD COLUMN IF NOT EXISTS content TEXT,
ADD COLUMN IF NOT EXISTS meta_title TEXT,
ADD COLUMN IF NOT EXISTS meta_description TEXT,
ADD COLUMN IF NOT EXISTS focus_keyword TEXT,
ADD COLUMN IF NOT EXISTS seo_score INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS related_slugs TEXT,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now());

-- Ensure is_published is boolean (if it was created differently)
-- If it doesn't exist, create it.
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'articles' AND column_name = 'is_published') THEN
        ALTER TABLE public.articles ADD COLUMN is_published BOOLEAN DEFAULT true;
    END IF;
END $$;

-- Table: clients
CREATE TABLE IF NOT EXISTS public.clients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_name TEXT NOT NULL,
    logo_path TEXT NOT NULL,
    display_order INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Table: gallery
CREATE TABLE IF NOT EXISTS public.gallery (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT,
    image_url TEXT NOT NULL,
    category TEXT DEFAULT 'General',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Table: users (Simple schema for legacy reference, Password hashes are NOT compatible)
CREATE TABLE IF NOT EXISTS public.legacy_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT,
    email TEXT,
    role TEXT,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- ==========================================
-- 2. DATA CLEANING
-- ==========================================

TRUNCATE TABLE public.services RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.testimonials RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.articles RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.clients RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.gallery RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.legacy_users RESTART IDENTITY CASCADE;

-- ==========================================
-- 3. DATA INSERTION
-- ==========================================

-- SERVICES
INSERT INTO public.services (title, slug, short_description, full_description, icon_svg, requirements, benefits, image_url, is_active) VALUES
(
    'Izin PPIU & PIHK', 
    'izin-ppiu-pihk', 
    'Pengurusan izin Penyelenggara Perjalanan Ibadah Umrah (PPIU) dan Penyelenggara Ibadah Haji Khusus (PIHK) dengan proses cepat dan legal.', 
    '<p class="MsoNormal"><strong>Apa Itu PPIU?</strong></p><p class="MsoNormal"><strong>PPIU</strong> adalah singkatan dari <strong>Penyelenggara Perjalanan Ibadah Umrah</strong>.</p><p class="MsoNormal">PPIU merupakan biro travel resmi yang telah memiliki izin dari Kementerian Agama Republik Indonesia untuk menyelenggarakan perjalanan ibadah umrah bagi masyarakat Indonesia.</p><p class="MsoNormal">Artinya, <strong>tidak semua travel bisa memberangkatkan umrah</strong>. Hanya travel yang berstatus <strong>PPIU berizin</strong> yang boleh menjual dan menjalankan paket umrah.</p><p class="MsoNormal"><strong>Lalu apa Itu PIHK?</strong></p><p class="MsoNormal"><strong>PIHK</strong> adalah singkatan dari <strong>Penyelenggara Ibadah Haji Khusus</strong>.</p><p class="MsoNormal">PIHK merupakan biro perjalanan resmi yang telah memiliki izin dari Kementerian Agama Republik Indonesia untuk menyelenggarakan ibadah Haji Khusus (ONH Plus).</p><p class="MsoNormal">⚠️ <strong>Catatan penting:</strong><br>PIHK <strong>fokus pada Haji Khusus</strong>, <strong>bukan umrah</strong>. Namun, dalam praktiknya banyak PIHK juga <strong>memiliki izin PPIU</strong>, sehingga dapat melayani <strong>umrah dan haji khusus sekaligus</strong>.</p>', 
    '<svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M3 21h18M5 21V7l8-4v18M13 21V3l8 4v14M9 9h1M9 13h1M9 17h1M17 9h1M17 13h1M17 17h1" /></svg>', 
    '<p>✔ Akta notaris pendirian perusahaan<br>✔ Susunan pengurus perusahaan<br>✔ NIB (Nomor Induk Berusaha) dan izin usaha biro perjalanan wisata aktif KBLI (79121) & (79122)<br>✔ Surat keterangan domisili usaha<br>✔ NPWP dan dokumen perpajakan lengkap<br>✔ Kantor fisik dengan bukti kepemilikan/sewa<br>✔ Bukti pengalaman usaha biro perjalanan wisata (calon BPW)</p>', 
    '<h2><strong>Mengapa Memilih Jamnasindo?</strong></h2><p><strong>Partner Strategis Legalitas Umrah & Haji</strong></p><p>✅ <strong>Kepastian Izin & Kepatuhan Regulasi</strong><br>Semua proses sesuai aturan resmi Kemenag, aman & terverifikasi.</p><p>✅ <strong>Minim Risiko, Tanpa Trial & Error</strong><br>Pendampingan berpengalaman, proses rapi, terhindar dari gagal izin & sanksi.</p><p>✅ <strong>Proses Cepat & Terarah</strong><br>Checklist jelas, timeline realistis, dan kontrol di setiap tahap.</p><p>✅ <strong>Bukan Sekadar Urus Izin</strong><br>Klien dibekali pemahaman regulasi & kesiapan bisnis jangka panjang.</p><p>✅ <strong>Meningkatkan Kredibilitas & Kepercayaan Pasar</strong><br>Travel lebih dipercaya jamaah, mitra, dan perbankan.</p>', 
    'uploads/services/srv_1770371165_6985b85d04c1a.png', 
    true
),
(
    'Izin Kontraktor', 
    'izin-kontraktor', 
    'Pengurusan Sertifikat Badan Usaha (SBU), Surat Izin Usaha Jasa Konstruksi (SIUJK), dan izin kontraktor lainnya.', 
    '<p>Jasa pengurusan SBU dan SIUJK terpercaya...</p>', 
    '<svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M2 20h20M4 20V10l8-6 8 6v10M10 20v-6h4v6" /><rect x="9" y="10" width="2" height="2" /><rect x="13" y="10" width="2" height="2" /></svg>', 
    NULL, 
    NULL, 
    NULL, 
    true
),
(
    'Izin Provider VISA', 
    'izin-provider-visa', 
    'Layanan pengurusan menjadi Provider Visa untuk berbagai keperluan bisnis, wisata, dan kunjungan kerja ke berbagai negara.', 
    '<p>Arab Saudi mengumumkan kebijakan baru terkait layanan <strong>visa umrah</strong> bagi Warga Negara Indonesia (WNI). Mulai <strong>23 November 2025</strong>, sistem <strong>virtual account untuk pengajuan visa umrah resmi ditutup</strong>, dan seluruh proses kini hanya dapat dilakukan melalui <strong>provider resmi</strong> yang memiliki kontrak aktif dengan pemerintah Arab Saudi.</p><p>Kebijakan ini menandai perubahan signifikan dalam proses administrasi ibadah umrah, khususnya bagi jamaah Indonesia yang jumlahnya termasuk salah satu yang terbesar di dunia.</p>', 
    '<svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="2" y="5" width="20" height="14" rx="2" /><path d="M2 10h20" /><path d="M6 15h4M14 15h4" /></svg>', 
    '<p>✔ Akta notaris pendirian perusahaan<br>✔ Susunan pengurus perusahaan</p><p>✔ NIB (Nomor Induk Berusaha) dan izin usaha biro perjalanan wisata aktif KBLI (79121) & (79122)<br>✔ Surat keterangan domisili usaha<br>✔ NPWP dan dokumen perpajakan lengkap<br>✔ Kantor fisik dengan bukti kepemilikan/sewa</p><p>✔ Buku Kontrak Kerjasama dengan Muassasah</p>', 
    '<h2><strong>Mengapa Memilih Jamnasindo?</strong></h2><p><strong>Partner Strategis Legalitas Umrah & Haji</strong></p><p>✅ <strong>Kepastian Izin & Kepatuhan Regulasi</strong><br>Semua proses sesuai aturan resmi Kemenag, aman & terverifikasi.</p><p>✅ <strong>Minim Risiko, Tanpa Trial & Error</strong><br>Pendampingan berpengalaman, proses rapi, terhindar dari gagal izin & sanksi.</p><p>✅ <strong>Proses Cepat & Terarah</strong><br>Checklist jelas, timeline realistis, dan kontrol di setiap tahap.</p><p>✅ <strong>Bukan Sekadar Urus Izin</strong><br>Klien dibekali pemahaman regulasi & kesiapan bisnis jangka panjang.</p><p>✅ <strong>Meningkatkan Kredibilitas & Kepercayaan Pasar</strong><br>Travel lebih dipercaya jamaah, mitra, dan perbankan.</p>', 
    NULL, 
    true
),
(
    'Akreditasi IATA', 
    'akreditasi-iata', 
    'Pendampingan dan pengurusan akreditasi IATA untuk agen perjalanan dan biro perjalanan wisata.', 
    '<p>Konsultasi akreditasi IATA untuk biro perjalanan...</p>', 
    '<svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M22 2L11 13M22 2l-7 20-4-9-9-4 20-7z" /></svg>', 
    NULL, 
    NULL, 
    NULL, 
    true
),
(
    'Bank Garansi', 
    'bank-garansi', 
    'Layanan pengurusan jaminan bank garansi untuk tender, proyek konstruksi, dan keperluan bisnis lainnya.', 
    '<p>Penerbitan Bank Garansi dan Surety Bond...</p>', 
    '<svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="8" width="18" height="12" rx="2" /><path d="M7 8V6a5 5 0 0110 0v2" /><circle cx="12" cy="14" r="2" /></svg>', 
    NULL, 
    NULL, 
    NULL, 
    true
),
(
    'Laporan Keuangan', 
    'laporan-keuangan', 
    'Jasa penyusunan laporan keuangan, audit, dan konsultasi perpajakan.', 
    '<p>Layanan pembukuan dan perpajakan profesional...</p>', 
    '<svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z" /><path d="M14 2v6h6M8 13h8M8 17h8M10 9h4" /></svg>', 
    NULL, 
    NULL, 
    NULL, 
    true
);

-- TESTIMONIALS
INSERT INTO public.testimonials (client_name, client_role, review_text, rating, photo_url, is_active) VALUES
('Ahmad Muharis', 'Direktur, PT Biro Perjalanan Wisata Muhsinin', 'Proses perizinan yang kami jalani bersama PT Jaminan Nasional Indonesia sangat rapi dan terarah. Kami merasa didampingi dari awal hingga selesai tanpa kebingungan.', 5, 'uploads/testimonials/testi_1770361326_698591eec2b38.jpeg', true),
('H. Abdullah Asad Basyaiban', 'Direktur Utama, PT Namirah Angkasa Jayatama', 'Timnya responsif, komunikatif, dan memahami regulasi dengan sangat baik. Legalitas perusahaan kami kini jauh lebih tertata.', 5, 'uploads/testimonials/testi_1770361448_69859268afebc.jpeg', true),
('Aam Hamroh', 'Direktur, PT Arruh Travel', 'Kami bisa fokus mengembangkan bisnis karena urusan perizinan dan kepatuhan ditangani secara profesional.', 5, 'uploads/testimonials/testi_1770361537_698592c13d782.jpeg', true),
('Rustam Sumarna', 'Direktur, PT Khalifah Tour', 'Pelayanan cepat, jelas, dan sesuai komitmen. Sangat membantu kami sebagai pelaku usaha yang ingin berkembang dengan aman.', 5, 'uploads/testimonials/testi_1770362386_69859612f159d.jpeg', true),
('Dwi Nopiyanti', 'Direktur, PT Dua Cahaya', 'PT Jaminan Nasional Indonesia memberikan rasa aman karena seluruh proses dijalankan sesuai regulasi yang berlaku.', 5, 'uploads/testimonials/testi_1770362550_698596b682639.jpeg', true),
('Lu''ai Arif', 'Direktur Utama, PT Faira Rihlah', 'Pendampingan yang diberikan bukan sekadar mengurus dokumen, tetapi juga memberikan pemahaman yang menyeluruh.', 5, 'uploads/testimonials/testi_1770362634_6985970acc6d3.jpeg', true),
('Tio Rizky Abadi', 'Komisaris, PT Zahrani Abadi Wisata', 'Sangat direkomendasikan bagi perusahaan yang ingin mengelola legalitas secara profesional dan berkelanjutan.', 5, 'uploads/testimonials/testi_1770362762_6985978a96250.jpeg', true),
('Ali Imran', 'Direktur, PT Zamani', 'Berkat pendampingan PT Jaminan Nasional Indonesia, proses perizinan usaha kami berjalan lancar dan tepat waktu.', 5, 'uploads/testimonials/testi_1770362876_698597fcedf38.jpeg', true),
('Ir. Biakto', 'Direktur Utama, PT Asfar Indo', 'Layanan yang diberikan mencerminkan pengalaman dan keahlian di bidang perizinan dan legalitas.', 5, 'uploads/testimonials/testi_1770362943_6985983f38611.jpeg', true),
('Devita Safiera', 'Direktur, PT Dwitunggal Jaya Wisata', 'Administrasi menjadi lebih tertib, rapi, dan sesuai standar yang dibutuhkan.', 5, 'uploads/testimonials/testi_1770363030_69859896da46d.jpeg', true);

-- ARTICLES
INSERT INTO public.articles (slug, title, category, author, image_url, content, read_time, meta_title, meta_description, focus_keyword, seo_score, is_published) VALUES
(
    'apa-itu-ppiu-berikut-penjelasan-secara-singkat-untuk-jamaah',
    'Apa itu PPIU? berikut penjelasan secara singkat untuk jamaah',
    'Perizinan',
    'admin',
    'uploads/thumbnails/thumb_1770280564_698456748e709.png',
    '<p class="MsoNormal"><strong>Apa Itu PPIU?</strong></p><p class="MsoNormal"><strong>PPIU</strong> adalah singkatan dari <strong>Penyelenggara Perjalanan Ibadah Umrah</strong>.</p><p class="MsoNormal">PPIU merupakan <strong>biro travel resmi</strong> yang <strong>telah memiliki izin dari Kementerian Agama Republik Indonesia</strong> untuk menyelenggarakan perjalanan ibadah umrah bagi masyarakat Indonesia.</p><p class="MsoNormal">Artinya, <strong>tidak semua travel bisa memberangkatkan umrah</strong>. Hanya travel yang berstatus <strong>PPIU berizin</strong> yang boleh menjual dan menjalankan paket umrah.</p><p class="MsoNormal"><strong>Tugas dan Tanggung Jawab PPIU</strong></p><p class="MsoNormal">Sebagai calon jemaah, penting tahu apa saja yang menjadi tanggung jawab PPIU, antara lain:</p><ol><li><strong>Pengurusan Visa Umrah</strong><br>Mengurus visa resmi sesuai ketentuan Arab Saudi.</li><li><strong>Tiket Pesawat Pergi–Pulang</strong><br>Dari Indonesia ke Arab Saudi dan kembali ke Indonesia.</li><li><strong>Akomodasi Hotel</strong><br>Hotel di Makkah dan Madinah sesuai paket yang ditawarkan.</li><li><strong>Transportasi Selama di Tanah Suci</strong><br>Antar bandara, hotel, dan lokasi ibadah.</li><li><strong>Pembimbing Ibadah (Muthawwif/Ustaz)</strong><br>Membimbing manasik dan ibadah selama umrah.</li><li><strong>Perlindungan & Tanggung Jawab Jemaah</strong><br>Termasuk asuransi dan kepastian keberangkatan.</li></ol><p class="MsoNormal"><strong>Kenapa Harus Memilih PPIU Resmi?</strong></p><p class="MsoNormal">Memilih PPIU berizin itu <strong>wajib</strong>, bukan sekadar saran.</p><p><strong>Kesimpulan</strong></p><p class="MsoNormal"><strong>PPIU adalah kunci utama perjalanan umrah yang aman dan nyaman.</strong><br>Sebelum mendaftar, pastikan travel pilihan Anda <strong>benar-benar PPIU resmi</strong>.</p>',
    '5 menit baca',
    'PPIU',
    'PPIU merupakan biro travel resmi yang telah memiliki izin dari Kementerian Agama Republik Indonesia untuk menyelenggarakan perjalanan ibadah umrah bagi masyarak',
    'Travel Umrah',
    0,
    true
),
(
    'apa-itu-pihk-apa-beda-nya-dengan-ppiu-',
    'Apa itu PIHK? apa beda nya dengan PPIU?',
    'Perizinan',
    'admin',
    'uploads/thumbnails/thumb_1770359651_69858b6395ba1.png',
    '<p class="MsoNormal"><strong>Apa Itu PIHK?</strong></p><p class="MsoNormal"><strong>PIHK</strong> adalah singkatan dari <strong>Penyelenggara Ibadah Haji Khusus</strong>.</p><p class="MsoNormal">PIHK merupakan <strong>biro perjalanan resmi</strong> yang <strong>telah memiliki izin dari Kementerian Agama Republik Indonesia</strong> untuk menyelenggarakan <strong>ibadah Haji Khusus (ONH Plus)</strong>.</p><p class="MsoNormal">⚠️ <strong>Catatan penting:</strong><br>PIHK <strong>fokus pada Haji Khusus</strong>, <strong>bukan umrah</strong>. Namun, dalam praktiknya banyak PIHK juga <strong>memiliki izin PPIU</strong>, sehingga dapat melayani <strong>umrah dan haji khusus sekaligus</strong>.</p>',
    '5 menit baca',
    'PIHK',
    'PIHK merupakan biro perjalanan resmi yang telah memiliki izin dari Kementerian Agama Republik Indonesia untuk menyelenggarakan ibadah Haji Khusus (ONH Plus).',
    'Travel Umrah dan Haji',
    0,
    true
),
(
    'mau-punya-bisnis-umrah-di-2026-ini-yang-harus-kamu-tahu-',
    'Mau Punya Bisnis Umrah di 2026? Ini yang Harus Kamu Tahu!',
    'Perizinan',
    'admin',
    'uploads/thumbnails/thumb_1770359635_69858b5396aea.png',
    '<p>Ingin punya <strong>biro travel umrah sendiri</strong> yang legal dan profitabel di 2026? Simak dulu semua <strong>syarat & langkah pentingnya</strong> di bawah ini.</p><p class="MsoNormal"><strong>1. Bentuk Badan Usaha yang Tepat</strong></p><p class="MsoNormal">👉 Bisnis umrah <strong>wajib didirikan dalam bentuk badan hukum</strong> seperti <strong>PT (Perseroan Terbatas) minimal berumur 1 tahun</strong> yang resmi terdaftar di Indonesia.</p><p class="MsoNormal"><strong>2. 📜 Pengajuan Izin Operasional PPIU ke Kemenhaj</strong></p><p class="MsoNormal">Kalau mau jadi <strong>Penyelenggara Perjalanan Ibadah Umrah (PPIU)</strong> yang sah, harus mengurus <strong>izin operasional</strong> dari <strong>Kementerian Haji dan Umrah RI</strong>.</p>',
    '5 menit baca',
    'Bisnis umrah 2026',
    'langkah langkah membuat izin PPIU',
    'Kementerian Haji dan Umrah',
    0,
    true
),
(
    'mengapa-akreditasi-penting-bagi-ppiu-dan-pihk-',
    'Mengapa Akreditasi penting bagi PPIU dan PIHK?',
    'Perizinan',
    'admin',
    'uploads/thumbnails/thumb_1770280533_69845655787b0.png',
    '<p><strong>APA ITU SERTIFIKASI PPIU dan PIHK ?</strong><br>Sertifikasi atau Akreditasi PPIU dan PIHK adalah rangkaian kegiatan penilaian kesesuaian yang berkaitan dengan pemberian jaminan tertulis bahwa pelayanan Penyelenggaraan Perjalanan Ibadah Umrah dan Penyelenggaraan Ibadah Haji Khusus telah memenuhi standar dan/atau regulasi.</p>',
    '5 menit baca',
    'Akreditasi PPIU dan PIHK',
    'perpanjangan izin umrah (PPIU) dan (PIHK)',
    'Sertifikasi travel umrah',
    0,
    true
),
(
    'menjelang-haji-2026-simak-jadwal-lengkap-biaya-bpih-dan-kuota-haji-reguler',
    'Menjelang Haji 2026 : Simak jadwal lengkap, Biaya BPIH, dan Kuota Haji Reguler',
    'Berita',
    'admin',
    'uploads/thumbnails/thumb_1770280452_698456045db94.png',
    '<h2><strong>Jadwal Lengkap Perjalanan Ibadah Haji 2026 (1447 H / 2026 M)</strong></h2><h3>📍 Tahapan Utama</h3><p><strong>Tahap persiapan hingga kepulangan:</strong></p><p>Artinya <strong>rangkaian perjalanan haji Indonesia berlangsung dari akhir April hingga akhir Juni 2026</strong>, dengan puncak ibadah di <strong>Arafah pada 26 Mei 2026</strong>.</p><h2><strong>Biaya Haji Indonesia 2026 (BPIH & Bipih)</strong></h2><p><strong>Penetapan resmi oleh Kementerian Haji dan Umrah RI (negara Indonesia):</strong></p><ul><li><p><strong>Total Biaya Penyelenggaraan Ibadah Haji (BPIH):</strong> Rp 87.409.365 per jamaah</p></li><li><p><strong>Biaya Perjalanan Ibadah Haji (Bipih) yang dibayar jamaah:</strong> Rp 54.193.806</p></li><li><p><strong>Nilai manfaat (subsidi/kontribusi lain):</strong> Rp 33.215.559</p></li></ul><p>💡 <em>Bipih adalah bagian yang dibayar langsung calon jamaah; sisanya berasal dari sumber lain seperti dana manfaat investasi haji dan APBN.</em></p><h2><strong>Kuota Haji Reguler Indonesia 2026</strong></h2><p>Total kuota nasional Indonesia untuk ibadah haji <strong>sekitar 221.000 jamaah</strong>.</p>',
    '5 menit baca',
    'Haji 2026',
    'Jadwal Lengkap Perjalanan Ibadah Haji 2026 dan Kuota Haji Reguler Indonesia 2026',
    'Jadwal haji 2026, dan biaya haji reguler',
    0,
    true
),
(
    'kemenhaj-bagikan-tips-praktis-agar-jemaah-terhindar-dari-penipuan-travel-umrah',
    'Kemenhaj Bagikan Tips Praktis Agar Jemaah Terhindar dari Penipuan Travel Umrah',
    'Berita',
    'admin',
    'uploads/thumbnails/thumb_1770177262_6982c2ee1b3d4.png',
    '<p>Dilansir dari Haji.go.id - </p><p>Kementerian Haji dan Umrah Republik Indonesia (Kemenhaj) terus mengedukasi masyarakat agar lebih waspada dan cermat dalam memilih travel umrah.</p><p><strong>Tips Praktis Menghindari Penipuan Travel Umrah</strong></p><p><strong>1. Verifikasi Legalitas Agen</strong></p><p>Pastikan travel terdaftar resmi sebagai Penyelenggara Perjalanan Ibadah Umrah (PPIU) melalui situs SATU HAJI.</p><p><strong>2. Periksa Reputasi dan Testimoni</strong></p><p>Telusuri ulasan jemaah sebelumnya.</p><p><strong>3. Tinjau Dokumen dan Biaya Secara Teliti</strong></p><p>Mintalah rincian biaya secara lengkap.</p><p><strong>4. Pilih Fasilitas dan Layanan yang Standar</strong></p><p>Pastikan travel menyediakan pembimbing ibadah bersertifikat.</p>',
    '5 menit baca',
    'Tips Terhindar Penipuan Travel',
    'Kemenhaj Bagikan Tips Praktis Agar Jemaah Terhindar dari Penipuan Travel Umrah',
    'Travel Umrah',
    0,
    true
);

-- CLIENTS
INSERT INTO public.clients (client_name, logo_path) VALUES
('1', 'assets/images/clients/client_1770256300_6983f7ac2f8d5.png'),
('2', 'assets/images/clients/client_1770256307_6983f7b34e593.png'),
('3', 'assets/images/clients/client_1770256315_6983f7bb22903.png'),
('4', 'assets/images/clients/client_1770256352_6983f7e0a27d3.png'),
('5', 'assets/images/clients/client_1770256357_6983f7e5d893b.png'),
('6', 'assets/images/clients/client_1770256362_6983f7ea3e598.png'),
('7', 'assets/images/clients/client_1770256367_6983f7ef22f77.png'),
('8', 'assets/images/clients/client_1770256372_6983f7f486562.png'),
('9', 'assets/images/clients/client_1770256376_6983f7f8bc798.png'),
('10', 'assets/images/clients/client_1770256381_6983f7fd368dc.png'),
('11', 'assets/images/clients/client_1770256386_6983f8027638b.png'),
('12', 'assets/images/clients/client_1770256391_6983f8077f682.png'),
('13', 'assets/images/clients/client_1770256396_6983f80cc1cbc.png'),
('14', 'assets/images/clients/client_1770256401_6983f811e1e56.png'),
('15', 'assets/images/clients/client_1770256407_6983f817d8d5b.png'),
('16', 'assets/images/clients/client_1770256414_6983f81ebe92f.png'),
('17', 'assets/images/clients/client_1770256421_6983f8251da82.png'),
('18', 'assets/images/clients/client_1770256426_6983f82a64aaa.png'),
('19', 'assets/images/clients/client_1770256431_6983f82fd0585.png'),
('20', 'assets/images/clients/client_1770256437_6983f8355b76f.png'),
('21', 'assets/images/clients/client_1770256443_6983f83b0c7f2.png'),
('22', 'assets/images/clients/client_1770256457_6983f8492bba1.png'),
('23', 'assets/images/clients/client_1770256462_6983f84e80a1b.png'),
('24', 'assets/images/clients/client_1770256467_6983f8536530d.png'),
('25', 'assets/images/clients/client_1770256473_6983f8599a35d.png'),
('26', 'assets/images/clients/client_1770256479_6983f85f7c62d.png'),
('27', 'assets/images/clients/client_1770256483_6983f863f35e3.png'),
('28', 'assets/images/clients/client_1770256489_6983f869a0b8a.png'),
('29', 'assets/images/clients/client_1770256494_6983f86ecc861.png'),
('30', 'assets/images/clients/client_1770256499_6983f873a9861.png'),
('31', 'assets/images/clients/client_1770256504_6983f87822559.png'),
('32', 'assets/images/clients/client_1770256509_6983f87d1a76c.png'),
('33', 'assets/images/clients/client_1770256515_6983f8832fe75.png'),
('34', 'assets/images/clients/client_1770256522_6983f88a5777f.png'),
('35', 'assets/images/clients/client_1770256529_6983f8913582a.png'),
('36', 'assets/images/clients/client_1770256535_6983f897679aa.png'),
('37', 'assets/images/clients/client_1770256540_6983f89cda97a.png'),
('38', 'assets/images/clients/client_1770256545_6983f8a14ef24.png'),
('39', 'assets/images/clients/client_1770256551_6983f8a78b9db.png'),
('40', 'assets/images/clients/client_1770256556_6983f8acaf291.png'),
('41', 'assets/images/clients/client_1770256562_6983f8b2e6a62.png'),
('42', 'assets/images/clients/client_1770256568_6983f8b8660cf.png'),
('43', 'assets/images/clients/client_1770256573_6983f8bd50962.png'),
('44', 'assets/images/clients/client_1770256578_6983f8c216838.png'),
('45', 'assets/images/clients/client_1770256583_6983f8c75d44d.png'),
('46', 'assets/images/clients/client_1770256588_6983f8ccc338b.png'),
('47', 'assets/images/clients/client_1770256593_6983f8d1433e2.png'),
('48', 'assets/images/clients/client_1770256598_6983f8d6edbf6.png'),
('49', 'assets/images/clients/client_1770256603_6983f8db52c57.png'),
('50', 'assets/images/clients/client_1770256836_6983f9c4b378c.png');

-- GALLERY
INSERT INTO public.gallery (title, image_url, category) VALUES
('PT Biro Perjalanan Wisata Muhsinin', 'uploads/gallery/gal_1770103758_6981a3ceeaf35.jpeg', 'General'),
('PT Namirah Angkasa Jaya Tama', 'uploads/gallery/gal_1770185867_6982e48b62533.jpeg', 'General'),
('PT Arraudah Utama Haramain', 'uploads/gallery/gal_1770185901_6982e4ad58518.jpeg', 'General'),
('PT Arsyila Wahyu Travel', 'uploads/gallery/gal_1770185919_6982e4bf50781.jpeg', 'General'),
('PT Cemerlang Hajar Aswad', 'uploads/gallery/gal_1770185947_6982e4db4b53e.jpeg', 'General'),
('PT Citra Ceria Usaha Khalifah', 'uploads/gallery/gal_1770185965_6982e4ed46f8f.jpeg', 'General'),
('PT Berkah Cahaya Haramain', 'uploads/gallery/gal_1770186016_6982e52035043.jpeg', 'General'),
('PT Faira Rihlah Islami', 'uploads/gallery/gal_1770186033_6982e531c449c.jpeg', 'General'),
('PT Garis Lurus Lintas Semesta', 'uploads/gallery/gal_1770186054_6982e54632d95.jpeg', 'General'),
('PT Mahabbah Fairuza Wisata', 'uploads/gallery/gal_1770186070_6982e556df35e.jpeg', 'General'),
('PT Hikami Mandiri Indonesia', 'uploads/gallery/gal_1770186087_6982e5676e420.jpeg', 'General'),
('PT Kemilau Karya Wisata', 'uploads/gallery/gal_1770186103_6982e57759ebd.jpeg', 'General'),
('PT Gamma Star Holiday', 'uploads/gallery/gal_1770186124_6982e58ccd61f.jpeg', 'General'),
('PT Kencana Raudhah Jaya', 'uploads/gallery/gal_1770186145_6982e5a108014.jpeg', 'General'),
('PT Jazira Halal Wisata', 'uploads/gallery/gal_1770186168_6982e5b8f1b4a.jpeg', 'General'),
('PT Mubarak Haramain Internasional', 'uploads/gallery/gal_1770186194_6982e5d2e65d1.jpeg', 'General'),
('PT Shabilla Eraldo Utama', 'uploads/gallery/gal_1770186221_6982e5ed1232f.jpeg', 'General'),
('PT Jana Madinah Wisata', 'uploads/gallery/gal_1770186242_6982e60296df0.jpeg', 'General'),
('PT Surya Fajar Wisata', 'uploads/gallery/gal_1770186259_6982e613da742.jpeg', 'General'),
('PT Zahrani Abadi Wisata', 'uploads/gallery/gal_1770186311_6982e6477c3f6.jpeg', 'General'),
('PT Maslahatul Ummah Internasional', 'uploads/gallery/gal_1770186330_6982e65a33d96.jpeg', 'General'),
('PT Oranye Patria Wisata', 'uploads/gallery/gal_1770186353_6982e6712792c.jpeg', 'General'),
('PT Redho Illahi Wisata', 'uploads/gallery/gal_1770186376_6982e6881fc54.jpeg', 'General'),
('PT Rindu Baitullah Tour & Travel', 'uploads/gallery/gal_1770186392_6982e698bf598.jpeg', 'General'),
('PT Wisata Putra Al Irshad', 'uploads/gallery/gal_1770186408_6982e6a8268b8.jpeg', 'General'),
('PT Annur Insani Rahmatan', 'uploads/gallery/gal_1770186430_6982e6be6284b.jpeg', 'General'),
('PT Asfar Indo Asa Barokah', 'uploads/gallery/gal_1770186447_6982e6cf18c0d.jpeg', 'General'),
('PT Baitulloh Cahaya Wisata', 'uploads/gallery/gal_1770186462_6982e6dec5373.jpeg', 'General'),
('PT Biro Perjalanan Wisata Zamani Amanah Mulia', 'uploads/gallery/gal_1770186476_6982e6ec7ee61.jpeg', 'General'),
('PT Dwitunggal Jaya Wisata', 'uploads/gallery/gal_1770186487_6982e6f7d4d65.jpeg', 'General'),
('PT Hafila Assalama Wisata', 'uploads/gallery/gal_1770186502_6982e706e1668.jpeg', 'General'),
('PT Harco Tour dan Travel', 'uploads/gallery/gal_1770186516_6982e71421ec3.jpeg', 'General'),
('PT Jabal Rahmah Anugerah', 'uploads/gallery/gal_1770186533_6982e725c1d73.jpeg', 'General'),
('PT MDA Wisata Travelindo', 'uploads/gallery/gal_1770186573_6982e74d936fc.jpeg', 'General'),
('PT Mina Arafah Myor', 'uploads/gallery/gal_1770186595_6982e7631b7fe.jpeg', 'General'),
('PT Musa Amanah Wisata', 'uploads/gallery/gal_1770186619_6982e77b662fc.jpeg', 'General'),
('PT Nawita Internasional Berkah', 'uploads/gallery/gal_1770186634_6982e78a15e61.jpeg', 'General'),
('PT Nazhirah Mumtaz Wisata', 'uploads/gallery/gal_1770186647_6982e7972e542.jpeg', 'General'),
('PT Seven Sky View', 'uploads/gallery/gal_1770186659_6982e7a337100.jpeg', 'General'),
('PT Syahara Berkah Mulia', 'uploads/gallery/gal_1770186675_6982e7b31fa47.jpeg', 'General'),
('PT Wisata Ziarah Muslim', 'uploads/gallery/gal_1770186692_6982e7c447ee2.jpeg', 'General'),
('PT Sinaya Amanah Wisata', 'uploads/gallery/gal_1770186769_6982e81121f01.jpeg', 'General');

-- USERS (Reference Only)
INSERT INTO public.legacy_users (username, email, role) VALUES 
('admin', 'admin@jamnasindo.id', 'admin'),
('ibnu', 'jamnasindo.info@gmail.com', 'editor');
